#! /bin/bash

if [ -z "$BUCKET" ]; then
    echo "ERROR: S3 bucket name not configured!"
    echo "Please set the \$BUCKET environment variable."
    echo "Example:"
    echo "\$ export BUCKET=YourAWSBucketName"
    
else
    echo "Updating from S3: $BUCKET"
    aws s3 sync s3://$BUCKET/S3/assets/js/ ~/workspace/S3WebApp/S3/assets/js/
fi